version: "3.9"
services:
           
  db:
    container_name: db
    image: postgres:15.1-alpine
    restart: always
    ports: 
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - .db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "5050:5050"
    env_file:
      - .env

  app:
    container_name: data-cent
    image: rappdw/docker-java-python:latest
    build: .
    volumes:
      - .:/code